(function() {
  const colors = (["red", "yellow", "blue", "green"]);
  let socket;
  window.addEventListener("load", main);

  function main() {
    if (!window.sessionStorage.getItem("color")) {
      window.sessionStorage.setItem("color", colors[Math.floor(Math.random() * colors.length)]);
    }
  
    document.getElementById("name-entry-container").classList.add(window.sessionStorage.getItem("color"));
    document.querySelector("#name-entry-container button").addEventListener("click", createWebSocket);
  }

  /**
   * Creates the web socket used to communicate with the game server.
   */
  function createWebSocket() {
    // create the web socket with our host
    // send it the game, and our name
    // set up responses and save it somewhere (idk where though :( )
    console.log("cool!");
    let socketUrl = "";
    if (window.location.protocol === "https:") {
      socketUrl += "wss://";
    } else {
      socketUrl += "ws://";
    }

    socketUrl += window.location.host;
    socket = new WebSocket(socketUrl);
    
    let name = document.getElementById("name-entry").value;
    if (!name || name.length <= 0) {
      name = "Default Daniel";
    }

    let game = "";
    window.location.search.substr(1)
      .split("&")
      .forEach(function(e) {
        let arg = e.split("=");
        if (arg[0] === "id") {
          game = arg[1];
        }
    });

    if (game.length === 0) {
      console.error("no game id found!");
    } else {
      let packet = {
        "name": name,
        "game": game
      };

      socket.onopen = () => {
        socket.send(JSON.stringify(packet));
      };

      socket.addEventListener("message", socketHandleEvent);
    }
  }

  /**
   * Called whenever our socket receives an event.
   * @param {MessageEvent} event - event generated by a socket message. 
   */
  function socketHandleEvent(event) {
    console.log(event);
    let packet = JSON.parse(event.data);
    console.log(packet.content);
    switch (packet.type) {
      case "readyinfo":
        console.log("READYINFO");
        updateReadyState(packet.content);
    }
  }

  /**
   * Called whenever the socket receives an update pertaining to the ready state of players.
   * @param {Array} content - an array of user names.
   */
  function updateReadyState(content) {
    console.log(content);
    console.log("i was called");
  }
})();